name: BidGadget CI

on:
  push:
  pull_request:

jobs:
  test-java:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Unit Test
        run: mvn clean test